### ISSUE TITLE
Error: gas required exceeds allowance or always failing transaction

### ISSUE THREAD

**Issue by rrodriguezreche** [JoinColony/colonyJS#377]
Hi, I am trying to run through your get started tutorials, I have applied for your feedback videos, but cannot get very far due to this error:

```
{ Error: gas required exceeds allowance or always failing transaction
    at getResult (/home/mad/personal/colony/node_modules/@colony/colony-js-client/node_modules/ethers/providers/json-rpc-provider.js:34:21)
    at exports.XMLHttpRequest.request.onreadystatechange (/home/mad/personal/colony/node_modules/@colony/colony-js-client/node_modules/ethers/providers/provider.js:621:30)
    at exports.XMLHttpRequest.dispatchEvent (/home/mad/personal/colony/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/home/mad/personal/colony/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/home/mad/personal/colony/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1132:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
  code: -32000,
  data: undefined,
  url: 'https://rinkeby.infura.io/',
  body:
   '{"method":"eth_estimateGas","params":[{"from":"0xe9Bc162930D5C96E27Ca67973a2e7d00f1f8B04f","to":"0xac83F8b1e046c15961c19A43979C01397f317287","data":"0x97304ced0000000000000000000000000000000000000000000000000000000000002710"}],"id":42,"jsonrpc":"2.0"}',
  responseText:
   '{"jsonrpc":"2.0","id":42,"error":{"code":-32000,"message":"gas required exceeds allowance or always failing transaction"}}' }
```

This is the whole script I am trying to use, for task 2 => "Using the colony and token you set up on Rinkeby from Task 1, please fund your colony by minting 10,000 tokens and claim them into your Colony."

```
const { getNetworkClient } = require("@colony/colony-js-client");
const { open } = require("@colony/purser-software");
const BN = require("bn.js");

(async () => {
  // Step 1: Open Wallet

  // Get a wallet instance
  const wallet = await open({
    privateKey:
      "notGonnaPutAPrivateKeyInTheOpen:D"
  });

  // Check out the logs to see the wallet address
  console.log("Wallet Address:", wallet.address);

  // Step 2: Get Network Client

  // Get a network client instance
  const networkClient = await getNetworkClient("rinkeby", wallet);

  // Check out the logs to see the network address
  console.log("Network Address:", networkClient.contract.address);

  // Step 5: Get Colony Client

  const colonyAddress = "0xac83F8b1e046c15961c19A43979C01397f317287";

  // Get a colony client instance using the network client instance
  const colonyClient = await networkClient.getColonyClientByAddress(
    colonyAddress
  );
  console.log(colonyClient);

  // Mint the tokens for the colony

  const amount = new BN(10000);

  const mintResponse = await colonyClient.mintTokens.send({
    amount
  });
  console.log(mintResponse);

  // Claim the funds for the colonyClient

  colonyClient.claimColonyFunds({
    token: "0x0D861eeCDd910Fcb18d83D521D62865fd3854cB9"
  });
})()
  .then(() => process.exit())
  .catch(error => console.error(error));
```
Using node: v11.11.0
Yarn: 1.13.0

Is there something I might be doing super wrong? I can be terribly noob sometimes.

**Comment by ryanchristo** [comment]
@rrodriguezreche Hi there!

It looks like the `gasLimit` is not being calculated correctly in colonyJS. I will take a look and see if I can get this fixed ASAP. In the meantime, you can set the `gasLimit` manually in the options for the transaction like so:

```
  const mintResponse = await colonyClient.mintTokens.send({
    amount
  }, { gasLimit: 100000 });
```
Sorry for the inconvenience! Let me know if you have any other questions.

**Comment by ryanchristo** [comment]
@rrodriguezreche This is a bit strange that you are receiving this error rather than a revert error but I just tried running through a fresh setup and got the same error when I did not set the token owner as the colony address and was able to successfully perform `mintTokens` afterwards.

Did you set the token owner as the colony address? For example:

```
  const setOwner = await colonyClient.tokenClient.setOwner.send({
    owner: colonyAddress,
  });
```

[Here](https://docs.colony.io/colonyjs/topics-tokens-and-funding/#set-token-owner)  is a link to the explanation in the docs. Let me know if that solves the issue. I think we still need to figure out why it was not throwing a revert error and instead we got the error posted above.

**Comment by ryanchristo** [comment]
@rrodriguezreche Did setting the token owner resolve the issue?

**Comment by rrodriguezreche** [comment]
@ryanchristo Hi! Sorry for the delay, I could not get to this until late yesterday. Yes, this has solved the issue and I 've been able to continue with the getting started and survey. Thank you a lot for the support! :100:

**Comment by rrodriguezreche** [comment]
Hi again @ryanchristo ! I thought I might be commenting here instead of opening another issue, although I saw that you marked this for closure, so if you might want to discuss this in another issue I will gladly go and open a new one.

The thing is I am getting the same error trying to call makePayment. This time I went a little further based on what I learnt here and checked out that I was complying with the roles. Thing is I am getting a positive ADMIN_ROLE when calling hasUserRole both for OneTxPayment and the founder wallet, but still it seems like I am out of luck when making the payment.

```
const { getNetworkClient } = require("@colony/colony-js-client");
const { open } = require("@colony/purser-software");
const BN = require("bn.js");
const path = require("path");
const fs = require("fs-extra");

(async () => {
  const FOUNDER_ROLE = "FOUNDER";
  const ADMIN_ROLE = "ADMIN";

  const OneTxPaymentAddress = "0xD447E2a66f50EB067a9bFe52296354C629fD2214";

  // Open Wallet
  const privateKey = fs.readFileSync("./private-key.txt", "utf8").trim();

  // Get a wallet instance
  const wallet = await open({
    privateKey
  });

  // Check out the logs to see the wallet address
  console.log("Wallet Address:", wallet.address);

  // Step 2: Get Network Client

  // Get a network client instance
  const networkClient = await getNetworkClient("rinkeby", wallet);

  // Check out the logs to see the network address
  console.log("Network Address:", networkClient.contract.address);

  // Get colony client

  const { colonyAddress, tokenAddress } = fs.readJsonSync(
    "./generated_data/addresses.json",
    "utf8"
  );
  console.log(`Colony address: ${colonyAddress}`);
  console.log(`Token address address: ${tokenAddress}`);

  // Get a colony client instance using the network client instance
  const colonyClient = await networkClient.getColonyClientByAddress(
    colonyAddress
  );

  const OneTxPaymentAddressHasAdminRole = await colonyClient.hasUserRole.call({
    user: OneTxPaymentAddress,
    role: ADMIN_ROLE
  });

  if (OneTxPaymentAddressHasAdminRole.hasRole === true)
    console.log(`OneTxPayment has admin role`);
  else console.log(`OneTxPayment does NOT have admin role`);

  const FounderHasAdminRole = await colonyClient.hasUserRole.call({
    user: wallet.address,
    role: ADMIN_ROLE
  });

  if (FounderHasAdminRole.hasRole === true)
    console.log(`Founder has admin role`);
  else console.log(`Founder does NOT have admin role`);

  const domainData = fs.readJsonSync("./generated_data/domain.json", "utf8");

  const fromPot = 1;
  const toPot = domainData.eventData.potId;
  const amount = new BN(10);
  const token = tokenAddress;

  const moveFundsResponse = await colonyClient.moveFundsBetweenPots.send({
    fromPot,
    toPot,
    amount,
    token
  });

  if (moveFundsResponse && moveFundsResponse.successful === true) {
    console.log("Funds moved successfully");
  }
  console.log(moveFundsResponse);

  const worker = "0xDCF7bAECE1802D21a8226C013f7be99dB5941bEa";
  const domainId = domainData.eventData.domainId;
  skillId = domainData.eventData.skillId;

  const makePaymentResponse = await colonyClient.makePayment.send({
    worker,
    token,
    amount,
    domainId,
    skillId
  });

  console.log(makePaymentResponse);
})()
  .then(() => process.exit())
  .catch(error => {
    console.error(error);
    process.exit();
  });
```

I 've uploaded a repo reproducing this. You can checkout at https://github.com/rrodriguezreche/colony-makepayment-issue-gas . 

I went all in (wooho) and checked the solidity codes, and observed that OneTxPayment is trying to call .makePayment in a Colony contract, but could not find that function anywhere, so I wonder if it is there where the issue might be, although I observed an EtherRouter pattern and maybe you are "injecting" it somewhere else, those topics are still a bit advanced for me.

```
pragma solidity >=0.4.23 <0.5.0;
pragma experimental ABIEncoderV2;

import "./../IColony.sol";
import "./../../lib/dappsys/roles.sol";


contract OneTxPayment {
  function makePayment(address _colony, address _worker, address _token, uint256 _amount, uint256 _domainId, uint256 _skillId) public {
    IColony colony = IColony(_colony);

    // Check caller is able to call makePayment on the colony
    // msg.sig is the same for this call as it is for the one we make below, so may as well use it here
    DSRoles authority = DSRoles(colony.authority());
    require(
      authority.canCall(
        msg.sender,
        _colony,
        bytes4(keccak256("makePayment(address,address,uint256,uint256,uint256)"))
      ),
      "colony-one-tx-payment-not-authorized"
    );

    // Make payment
    colony.makePayment(_worker, _token, _amount, _domainId, _skillId);
  }


}
```

**Comment by ryanchristo** [comment]
Hey hey! Following up here works for me.

Yup, sorry about the error message. This is happening because we are estimating the transaction cost before executing the transaction and therefore receiving the error from the estimate, which is not the usual revert error that would be more specific. We are working on a solution to show the revert error.

My first guess would be that the domain assigned to the payment method does not have the tokens to make the payment. Try running this before the `makePayment` method:

```
  // Get pot balance
  const potBalance = await colonyClient.getFundingPotBalance.call({
    potId: domainData.eventData.potId,
    token,
  })

  // Check out the logs to see the pot balance
  console.log('potBalance', potBalance.toNumber());
```

**Comment by ryanchristo** [comment]
If not that, you might be using a `skillId` that does not exist. The `skillId` should reference a global skill and it looks like you might be referencing the `localSkillId` of the domain. Another solution might be changing the `skillId` in the `makePayment` method to `1`.

**Comment by rrodriguezreche** [comment]
Oh alright, it was the skill which was failing as you said. Thank you for helping me complete the survey, I guess that was cheating... sort of :P
