### ISSUE TITLE
Make failing tests pass (or skip/remove invalid tests)

### ISSUE THREAD

**Issue by JamesLefrere** [JoinColony/colonyJS#8]
Entire log as follows:

```
 yarn run test
yarn run v1.3.2
$ flow check && lerna run test
Found 0 errors
lerna info version 2.5.1
lerna info versioning independent

> @colony/colony-js-adapter@1.0.0 test /Users/james/colony/colony-js/packages/colony-js-adapter
> echo 'Error: no test specified'

Error: no test specified
lerna ERR! test Errored while running script in '@colony/colony-js-client'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run test
lerna ERR! error Command failed with exit code 1.
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 1
lerna ERR! npm ERR! @colony/colony-js-client@1.0.0 test: `yarn run lint && yarn run test:unit`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR!
lerna ERR! npm ERR! Failed at the @colony/colony-js-client@1.0.0 test script.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     /Users/james/.npm/_logs/2018-01-11T14_05_57_817Z-debug.log
lerna ERR!
lerna ERR! > @colony/colony-js-client@1.0.0 test /Users/james/colony/colony-js/packages/colony-js-client
lerna ERR! > yarn run lint && yarn run test:unit
lerna ERR!
lerna ERR! $ eslint src
lerna ERR!
lerna ERR! /Users/james/colony/colony-js/packages/colony-js-client/src/__tests__/Contract.test.js
lerna ERR!   24:12  error  Unexpected dangling '_' in '_adapter'  no-underscore-dangle
lerna ERR!
lerna ERR! /Users/james/colony/colony-js/packages/colony-js-client/src/index.js
lerna ERR!    1:10  error  Prefer default export                import/prefer-default-export
lerna ERR!   13:1   error  More than 2 blank lines not allowed  no-multiple-empty-lines
lerna ERR!
lerna ERR! ✖ 3 problems (3 errors, 0 warnings)
lerna ERR!   1 error, 0 warnings potentially fixable with the `--fix` option.
lerna ERR!
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR!
lerna ERR!     at Promise.all.then.arr (/Users/james/colony/colony-js/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.

> @colony/colony-js-adapter-ethers@1.0.0 test /Users/james/colony/colony-js/packages/colony-js-adapter-ethers
> yarn run lint && yarn run test:unit

$ eslint src
$ jest --coverage --config=jest.conf.json
------------|----------|----------|----------|----------|----------------|
File        |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------|----------|----------|----------|----------|----------------|
All files   |      100 |      100 |      100 |      100 |                |
 Adapter.js |      100 |      100 |      100 |      100 |                |
 index.js   |      100 |      100 |      100 |      100 |                |
------------|----------|----------|----------|----------|----------------|
(node:31570) UnhandledPromiseRejectionWarning: Error: Command failed: npm run test
error Command failed with exit code 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @colony/colony-js-client@1.0.0 test: `yarn run lint && yarn run test:unit`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @colony/colony-js-client@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/james/.npm/_logs/2018-01-11T14_05_57_817Z-debug.log

> @colony/colony-js-client@1.0.0 test /Users/james/colony/colony-js/packages/colony-js-client
> yarn run lint && yarn run test:unit

$ eslint src

/Users/james/colony/colony-js/packages/colony-js-client/src/__tests__/Contract.test.js
  24:12  error  Unexpected dangling '_' in '_adapter'  no-underscore-dangle

/Users/james/colony/colony-js/packages/colony-js-client/src/index.js
   1:10  error  Prefer default export                import/prefer-default-export
  13:1   error  More than 2 blank lines not allowed  no-multiple-empty-lines

✖ 3 problems (3 errors, 0 warnings)
  1 error, 0 warnings potentially fixable with the `--fix` option.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (/Users/james/colony/colony-js/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:31570) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:31570) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by JamesLefrere** [comment]
Sorted.
